name: Check Unit Testing

on: [pull_request]

jobs:
  python-tests:
    name: Testing Check
    runs-on: ubuntu-latest
    steps:
      - name: clone-repo
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: install-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: install-requirements
        run: |
          python -m pip install -r requirements-develop.txt
          python -m pip install -e .
      - name: test-check
        run: |
          bash check-unit-tests.sh
          bash check-coverage.sh
