name: Hello Test

on: [pull_request]

jobs:
  python-hello:
    name: Check Basic Hello-World Command
    runs-on: ubuntu-latest
    steps:
      - name: clone-repo
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: install-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: build-dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel
      - name: python-wheel
        run: |
          python setup.py bdist_wheel
      - name: opalina-install
        run: |
          python -m pip install ./dist/opalina*.whl
      - name: hello-world-test
        run: |
          python -m opalina hello
