name: Check Python Types

on: [pull_request]

jobs:
  python-types:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - name: clone-repo
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: install-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: install-requirements
        run: python -m pip install -r requirements-develop.txt
      - name: style-check
        run: bash check-types.sh
