name: PyPI Publish

on:
  pull_request:
    types:
      - closed
    branches:
      - prod

jobs:
  python-publish:
    if: github.event.pull_request.merged == true
    name: Python Package Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Twine
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel twine
      - name: Build and Publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist
          twine upload -u ${TWINE_USERNAME} -p ${TWINE_PASSWORD} --skip-existing dist/*

